// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlq0CGzDGMAXshBBS4wXuG20aoC9KMgiE',
    appId: '1:380455043349:web:0c7caf7f9ccba9291be91c',
    messagingSenderId: '380455043349',
    projectId: 'shakti-a2be9',
    authDomain: 'shakti-a2be9.firebaseapp.com',
    storageBucket: 'shakti-a2be9.firebasestorage.app',
    measurementId: 'G-6R4CNHXWKF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFKTJBOMSDPw3vgrk4Gnafi-6zP_TtCE',
    appId: '1:380455043349:android:588159cb4ee9e83c1be91c',
    messagingSenderId: '380455043349',
    projectId: 'shakti-a2be9',
    storageBucket: 'shakti-a2be9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChGgR7qiuisF14ZQI4REu198JpaqO8x1A',
    appId: '1:380455043349:ios:d7dff69b5f7b31581be91c',
    messagingSenderId: '380455043349',
    projectId: 'shakti-a2be9',
    storageBucket: 'shakti-a2be9.firebasestorage.app',
    iosBundleId: 'com.example.shakti',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChGgR7qiuisF14ZQI4REu198JpaqO8x1A',
    appId: '1:380455043349:ios:d7dff69b5f7b31581be91c',
    messagingSenderId: '380455043349',
    projectId: 'shakti-a2be9',
    storageBucket: 'shakti-a2be9.firebasestorage.app',
    iosBundleId: 'com.example.shakti',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlq0CGzDGMAXshBBS4wXuG20aoC9KMgiE',
    appId: '1:380455043349:web:90f628d23d30dd2b1be91c',
    messagingSenderId: '380455043349',
    projectId: 'shakti-a2be9',
    authDomain: 'shakti-a2be9.firebaseapp.com',
    storageBucket: 'shakti-a2be9.firebasestorage.app',
    measurementId: 'G-8J0D7M54HZ',
  );
}
